version: '3.7'

services:
  database:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bims-db
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "miniominio"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"

  minio_createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: |
      /bin/bash -c "
      while ! echo "exit" | /usr/bin/curl -s telnet://minio:9000; do echo 'Wait minio to startup...' && sleep 0.1; done;
      /usr/bin/mc config host add minio http://minio:9000 minio miniominio;
      /usr/bin/mc mb minio/bims-files;
      /usr/bin/mc anonymous set public minio/bims-files;
      exit 0;
      "

volumes:
  database-data:
  minio-data:
