version: '3.7'

services:
  database:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bims-db
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
