name: Build and Push Docker Image

on:
  push:
    branches:
      - main

concurrency:
  group: build-docker-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --tag ghcr.io/kr-pokectr/bims:latest --label "runnumber=${GITHUB_RUN_ID}" .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: docker push ghcr.io/kr-pokectr/bims:latest
