name: Deploy to Staging

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          environment-url: https://staging.bims.pokecenter.me
          environment: staging

      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_HOST }}/bims-staging
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          command: deploy

      - uses: chrnorm/deployment-status@v2
        if: success()
        name: Update GitHub deployment status (success)
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - uses: chrnorm/deployment-status@v2
        if: failure()
        name: Update GitHub deployment status (failure)
        with:
          token: ${{ github.token }}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"
