name: E2E & Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: unit-test-${{ github.ref }}
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/bims-database?schema=public"
      SECRET_COOKIE_PASSWORD: "qLVhCjXDmd05ejEZVgFKYv8MkzwFcrrC"
      PLAYWRIGHT_TEST: "true"
    services:
      postgres:
        image: postgres:14-bullseye
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "bims-database"
      minio:
        image: bitnami/minio
        ports:
          - "9000:9000"
          - "9090:9090"
        env:
          MINIO_ROOT_USER: "minio"
          MINIO_ROOT_PASSWORD: "miniominio"
          MINIO_DEFAULT_BUCKETS: "bims-files"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Migrate database
        run: yarn prod:db:migrate
      - name: Seed database
        run: yarn db:seed
      - name: Run unit Tests
        run: yarn test
        env:
          AWS_S3_ACCESS_KEY_ID: minio
          AWS_S3_SECRET_ACCESS_KEY: miniominio
          AWS_S3_REGION: auto
          AWS_S3_ENDPOINT: http://localhost:9000
          AWS_S3_BUCKET: bims-files
          NODE_ENV: "test"
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
        env:
          AWS_S3_ACCESS_KEY_ID: minio
          AWS_S3_SECRET_ACCESS_KEY: miniominio
          AWS_S3_REGION: auto
          AWS_S3_ENDPOINT: http://localhost:9000
          AWS_S3_BUCKET: bims-files
          NODE_ENV: "test"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
      - name: Add Failure label
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && failure() }}
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['tests/failure']
              })
            } catch (e) {
              console.error(e);
            }

      - name: Remove Failure Label
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && success() }}
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'tests/failure'
              })
            } catch (e) {
              console.error(e);
            }
