name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 15
    runs-on: self-hosted
    env:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bims-database?schema=public"
      SECRET_COOKIE_PASSWORD: "qLVhCjXDmd05ejEZVgFKYv8MkzwFcrrC"
      PLAYWRIGHT_TEST: "true"
    services:
      postgres:
        image: postgres:14-bullseye
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "bims-database"
      minio:
        image: bitnami/minio
        ports:
          - "9000:9000"
          - "9090:9090"
        env:
          MINIO_ROOT_USER: "minio"
          MINIO_ROOT_PASSWORD: "miniominio"
          MINIO_DEFAULT_BUCKETS: "bims-files"
    container:
      image: mcr.microsoft.com/playwright:v1.30.0-focal

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn build
      - name: Migrate database
        run: yarn prod:db:migrate
      - name: Seed database
        run: yarn db:seed
      - name: Run Playwright tests
        run: yarn playwright test
        env:
          AWS_S3_ACCESS_KEY_ID: minio
          AWS_S3_SECRET_ACCESS_KEY: miniominio
          AWS_S3_REGION: auto
          AWS_S3_ENDPOINT: http://minio:9000
          AWS_S3_BUCKET: bims-files
          NODE_ENV: "production"
          HOME: /root # workaround https://github.com/microsoft/playwright/issues/6500
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run unit Tests
        run: yarn test
        env:
          AWS_S3_ACCESS_KEY_ID: minio
          AWS_S3_SECRET_ACCESS_KEY: miniominio
          NODE_ENV: "production"
